In [45]:
import numpy as np

In [46]:
from sklearn. datasets import load_iris
iris_dataset = load_iris()

In [47]:
print("First five rows of data:\n", iris_dataset['data'][9:19])

First five rows of data:
 [[4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]]


In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

In [49]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [50]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [51]:
#KNeighborsClassifier(algorithm='auto',leaf_size=30, metric='minkowski', metric_params=None, n_jobs=None, n_neighbors=1, p=2, weights='uniform')

In [52]:
X_new = np.array([[6.1, 2.6, 5.6, 1.4]])
print("X_new.shape:",X_new.shape)

X_new.shape: (1, 4)


In [53]:
prediction = knn.predict(X_new)
print("Prediction:", prediction)
print("Predicted target name:",
       iris_dataset['target_names'][prediction])

Prediction: [2]
Predicted target name: ['virginica']


In [54]:
X_new = np.array([[6,2.7,5.1,1.6]])
print("X_new.shape:",X_new.shape)

X_new.shape: (1, 4)


In [55]:
prediction = knn.predict(X_new)
print("Prediction:", prediction)
print("Predicted target name:",
       iris_dataset['target_names'][prediction])

Prediction: [2]
Predicted target name: ['virginica']
